[32m2024-10-07 10:50:24 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_0 - 049cb24d-956b-4b86-b33c-dd54586a8ccb - 72106 - LOGS_CAPTURED - Started capturing logs in process (pid: 72106).
[32m2024-10-07 10:50:24 +0200[0m - dagster - [34mDEBUG[0m - __ASSET_JOB_0 - 049cb24d-956b-4b86-b33c-dd54586a8ccb - 72106 - trips_by_week - STEP_START - Started execution of step "trips_by_week".
[32m2024-10-07 10:50:25 +0200[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB_0 - 049cb24d-956b-4b86-b33c-dd54586a8ccb - 72106 - trips_by_week - STEP_FAILURE - Execution of step "trips_by_week" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "trips_by_week"::

OSError: Cannot save file into a non-existent directory: 'data/outputs'

Stack Trace:
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_utils/__init__.py", line 473, in iterate_with_context
    next_output = next(iterator)
                  ^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 141, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
             ^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/dagster/_core/execution/plan/compute_generator.py", line 129, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster-and-dbt/dagster_university/assets/metrics.py", line 69, in trips_by_week
    aggregate.to_csv(constants.TRIPS_BY_WEEK_FILE_PATH, index=False)
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")

The above exception occurred during handling of the following exception:
FileNotFoundError: [Errno 2] No such file or directory: 'data/outputs/trips_by_week.csv'

Stack Trace:
  File "/home/me/dagster_dbt_tutorial/dagster-and-dbt/dagster_university/assets/metrics.py", line 64, in trips_by_week
    existing = pd.read_csv(constants.TRIPS_BY_WEEK_FILE_PATH)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/me/dagster_dbt_tutorial/dagster_dbt_tut_env/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
[0m
